# -*- mode: ruby -*-
# vi: set ft=ruby :

Vagrant.configure("2") do |config|

    hostname = "haskell.box"
    locale = "en_GB.UTF.8"

    # Box
    config.vm.box = "ubuntu/trusty64"

    # Shared folders
    config.vm.synced_folder ".", "/srv"

    # Setup
    config.vm.provision :shell, :inline => "touch .hushlogin"
    config.vm.provision :shell, :inline => "hostnamectl set-hostname #{hostname} && locale-gen #{locale}"
    config.vm.provision :shell, :inline => "apt-get update --fix-missing"
    config.vm.provision :shell, :inline => "apt-get install -q -y g++ make git curl vim"

    # Install stack
    config.vm.provision :shell, :inline => "wget -q -O- https://s3.amazonaws.com/download.fpcomplete.com/ubuntu/fpco.key | apt-key add -"
    config.vm.provision :shell, :inline => "echo 'deb http://download.fpcomplete.com/ubuntu/utopic stable main' | tee /etc/apt/sources.list.d/fpco.list"
    config.vm.provision :shell, :inline => "apt-get update && apt-get install -q -y stack"

    config.vm.provider "virtualbox" do |v|
        v.memory = 1024
    end
end
