# -*- mode: ruby -*-
# vi: set ft=ruby :

Vagrant.configure("2") do |config|

    hostname = "elm.box"
    locale = "en_US.UTF.8"

    # Box
    config.vm.box = "ubuntu/vivid64"

    # Shared folders
    config.vm.synced_folder ".", "/srv"

    # Setup
    config.vm.provision :shell, :inline => "touch .hushlogin"
    config.vm.provision :shell, :inline => "hostnamectl set-hostname #{hostname} && locale-gen #{locale}"
    config.vm.provision :shell, :inline => "apt-get update --fix-missing"
    config.vm.provision :shell, :inline => "apt-get install -q -y g++ make git curl vim"

    # Lang
    config.vm.provision :shell, :inline => "apt-get install -q -y nodejs-legacy"
    config.vm.provision :shell, :inline => "apt-get install -q -y npm"
    config.vm.provision :shell, :inline => "npm install --global elm"

    # Work around for elm install not working in virtual machines
    config.vm.provision :shell, :inline => "git clone https://gist.github.com/11d33acb137646b317d1.git"

    # VirtualBox
    config.vm.provider "virtualbox" do |v|
       v.memory = 1024
    end
end
