# -*- mode: ruby -*-
# vi: set ft=ruby :

Vagrant.configure(2) do |config|

  hostname = "mongo.box"
  locale = "en_US.UTF.8"


  # Box
  config.vm.box = "ubuntu/trusty64"

  # Sync local folder to vm
  config.vm.synced_folder ".", "/srv"

  # Network
  config.vm.network :forwarded_port, guest: 27017, host: 27017

  # Configure Ubuntu
  config.vm.provision :shell, :inline => "hostnamectl set-hostname #{hostname} && locale-gen #{locale}"
  config.vm.provision :shell, :inline => "apt-get update --fix-missing"
  config.vm.provision :shell, :inline => "apt-get install -q -y git curl vim"

  # Install MongoDB
  config.vm.provision :shell, :inline => "apt-key adv --keyserver hkp://keyserver.ubuntu.com:80 --recv 7F0CEB10"
  config.vm.provision :shell, :inline => "echo 'deb http://downloads-distro.mongodb.org/repo/ubuntu-upstart dist 10gen' | tee /etc/apt/sources.list.d/mongodb.list"
  config.vm.provision :shell, :inline => "apt-get update && apt-get install -q -y mongodb-org"

  # Configure MongoDB
  config.vm.provision :shell, :inline => "service mongod stop"
  config.vm.provision :shell, :inline => "mkdir -p /mnt/mongod"
  config.vm.provision :shell, :inline => "mkdir -p --mode=777 /data/db"
  config.vm.provision :shell, :inline => "cp /srv/mongod.conf /etc/mongod.conf"
  config.vm.provision :shell, :inline => "service mongod start"

  # Configure VirtualBox
  config.vm.provider "virtualbox" do |v|
    v.memory = 1024
    v.cpus = 2
  end

end
